name: PasticheOfSKin
favicon: null
layout_spectrum: 0.3695554081350565
typography_spectrum: 0.10216184961609542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8287442533764988
  lightness: 0.5095592611469328
  saturation: 0.2748093663249165
  rhythmicContrast: 0.48084300477057695
purpose: []
