name: PasticheOfSKin
favicon: null
layout_spectrum: 0.74741
typography_spectrum: 0.04353
title: 'Sideward glance at life, games and everything else'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a22071'
    - '#000000'
    - '#8a82be'
    - '#ffffff'
    - '#e4bcd4'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
